plugins:
  - jekyll-sitemap
theme: jekyll-theme-minimal

title: "Lazuly's Street Fighter memo"
description: "ロボコンオタクのスト6メモ"
logo: /mainSite/docs/img/icon.png
google_analytics: G-PN04M09J2X

twitter:
  username: lazuly_tech

